import React,{useMemo,useState} from "react";
import {HashRouter,useNavigate,useParams,Routes,Route,Link} from "react-router-dom";
import {allQuestions,getQuestionsByTopic,getQuestion} from "./data/questions";
import {subjects,chapters,topics} from "./data/curriculum";
import {useProgressStore} from "./store/progress";
import type {Question,ContentBlock} from "./types";
const subjectFor=(id:string)=>subjects.find(s=>s.id===id); const topicFor=(id:string)=>topics.find(t=>t.id===id);
const Shell=({children}:{children:React.ReactNode})=><><header className="topbar"><Link to="/" className="brand">JNVST कक्षा 9</Link><nav><Link to="/">डैशबोर्ड</Link><Link to="/subjects">विषय</Link><Link to="/bookmarks">बुकमार्क</Link><Link to="/mock-tests">मॉक टेस्ट</Link></nav></header><main className="shell">{children}</main></>;
const Card=({children,className=""}:{children:React.ReactNode,className?:string})=><div className={`card ${className}`}>{children}</div>;
const QuestionText=({blocks}:{blocks:ContentBlock[]})=><>{blocks.map((b,i)=>b.type==='paragraph'?<p key={i}>{b.text}</p>:b.type==='heading'?<h3 key={i}>{b.text}</h3>:b.type==='list'?<ul key={i}>{b.items.map(x=><li key={x}>{x}</li>)}</ul>:b.type==='formula'?<div key={i} className="formula">{b.expression}</div>:b.type==='step-by-step'?<ol key={i}>{b.steps.map(x=><li key={x}>{x}</li>)}</ol>:<div key={i} className="callout">{b.title&&<b>{b.title}</b>}<div>{b.text}</div></div>)}</>;
const Dashboard=()=>{const p=useProgressStore();const completed=Object.values(p.lessonActivity).filter(x=>x.status==='completed').length;const attempts=Object.values(p.questionAttempts).flat();const acc=attempts.length?Math.round(attempts.filter(x=>x.isCorrect).length/attempts.length*100):0;return <Shell><section className="hero"><div><span className="eyebrow">JAWAHAR NAVODAYA VIDYALAYA</span><h1>JNVST कक्षा 9 Learning Hub</h1><p>पढ़ें, अभ्यास करें, अपनी प्रगति देखें और 100 प्रश्नों वाले मॉक टेस्ट से तैयारी करें।</p><div className="actions"><Link className="btn primary" to="/subjects">पढ़ाई शुरू करें</Link><Link className="btn" to="/mock-tests">मॉक टेस्ट दें</Link></div></div><div className="hero-stat"><b>{allQuestions.length}</b><span>अभ्यास प्रश्न</span></div></section><section className="stats"><Card><b>{completed}</b><span>पूर्ण पाठ</span></Card><Card><b>{attempts.length}</b><span>प्रश्न प्रयास</span></Card><Card><b>{acc}%</b><span>सटीकता</span></Card><Card><b>{p.bookmarks.questionIds.length}</b><span>बुकमार्क</span></Card></section><h2>विषय</h2><div className="grid">{subjects.map(s=><Link key={s.id} to={`/subjects/${s.id}`}><Card className="subject-card"><div className="icon">{s.iconRef}</div><h3>{s.title}</h3><p>{s.description}</p><span className="linkish">विषय खोलें →</span></Card></Link>)}</div><h2>JNVST परीक्षा पैटर्न</h2><Card><div className="pattern"><div><b>अंग्रेज़ी</b><span>15 प्रश्न</span></div><div><b>हिंदी</b><span>15 प्रश्न</span></div><div><b>गणित</b><span>35 प्रश्न</span></div><div><b>सामान्य विज्ञान</b><span>35 प्रश्न</span></div><div className="total"><b>कुल</b><span>100 प्रश्न · 150 मिनट</span></div></div></Card></Shell>};
const SubjectsPage=()=> <Shell><div className="page-head"><h1>विषय</h1><p>किसी विषय का चयन करके अध्याय और टॉपिक तक जाएँ।</p></div><div className="grid">{subjects.map(s=><Link key={s.id} to={`/subjects/${s.id}`}><Card className="subject-card"><div className="icon">{s.iconRef}</div><h2>{s.title}</h2><p>{s.description}</p></Card></Link>)}</div></Shell>;
const SubjectPage=()=>{const {subjectId}=useParams();const s=subjectFor(subjectId||"");if(!s)return <Shell><Card><h1>विषय नहीं मिला</h1><Link to="/subjects">विषयों पर वापस जाएँ</Link></Card></Shell>;return <Shell><div className="page-head"><Link to="/subjects">← सभी विषय</Link><h1>{s.iconRef} {s.title}</h1><p>{s.description}</p></div>{chapters.filter(c=>s.chapterIds.includes(c.id)).map(c=><section key={c.id}><h2>{c.title}</h2><div className="grid">{c.topicIds.map(tid=>{const t=topicFor(tid)!;const count=allQuestions.filter(q=>q.topicId===tid).length;return <Link key={tid} to={`/practice/${tid}`}><Card><h3>{t.title}</h3><p>{count} प्रश्न उपलब्ध</p><span className="linkish">अभ्यास शुरू करें →</span></Card></Link>})}</div></section>)}</Shell>};
const Practice=()=>{const {topicId}=useParams();const qs=useMemo(()=>getQuestionsByTopic(topicId||""),[topicId]);const [idx,setIdx]=useState(0);const [sel,setSel]=useState<string[]>([]);const [checked,setChecked]=useState(false);const p=useProgressStore();if(!qs.length)return <Shell><Card className="empty"><h1>इस टॉपिक में प्रश्न उपलब्ध नहीं हैं</h1><Link className="btn" to="/subjects">विषयों पर जाएँ</Link></Card></Shell>;const q=qs[idx];const correct=sel.length===q.correctOptionIds.length&&sel.every(x=>q.correctOptionIds.includes(x));const toggle=(id:string)=>{if(checked)return;q.type==='mcq'||q.type==='true-false'?setSel([id]):setSel(sel.includes(id)?sel.filter(x=>x!==id):[...sel,id])};const next=()=>{p.recordAttempt(q.id,sel,correct);if(idx===qs.length-1){setIdx(idx)}else{setIdx(idx+1);setSel([]);setChecked(false)}};const bookmarked=p.bookmarks.questionIds.includes(q.id);return <Shell><div className="page-head"><Link to={`/subjects/${q.subjectId}`}>← विषय</Link><div className="progressline"><span>प्रश्न {idx+1} / {qs.length}</span><span className={`badge ${q.difficulty}`}>{q.difficulty}</span></div></div><Card className="quiz"><div className="quiz-tools"><button className="bookmark" onClick={()=>p.toggleBookmarkQuestion(q.id)}>{bookmarked?"★ बुकमार्क किया":"☆ बुकमार्क करें"}</button></div><QuestionText blocks={q.text}/><div className="options">{q.options.map(o=><button key={o.id} className={`option ${sel.includes(o.id)?'selected':''} ${checked&&q.correctOptionIds.includes(o.id)?'correct':''} ${checked&&sel.includes(o.id)&&!q.correctOptionIds.includes(o.id)?'wrong':''}`} onClick={()=>toggle(o.id)}><span className="radio">{sel.includes(o.id)?'✓':''}</span>{o.text}</button>)}</div>{checked&&<div className={`feedback ${correct?'good':'bad'}`}><b>{correct?'सही उत्तर':'गलत उत्तर'}</b><QuestionText blocks={q.explanation}/></div>}<div className="quiz-actions">{!checked?<button className="btn primary" disabled={!sel.length} onClick={()=>setChecked(true)}>उत्तर जाँचें</button>:<button className="btn primary" onClick={next}>{idx===qs.length-1?'अंतिम प्रश्न':'अगला प्रश्न'}</button>}</div></Card></Shell>};
const Bookmarks=()=>{const ids=useProgressStore(s=>s.bookmarks.questionIds);const qs=ids.map(getQuestion).filter(Boolean) as Question[];return <Shell><div className="page-head"><h1>बुकमार्क</h1><p>बाद में दोहराने के लिए सुरक्षित किए गए प्रश्न।</p></div>{qs.length?<div className="grid">{qs.map(q=><Card key={q.id}><QuestionText blocks={q.text}/><div className="actions"><Link className="btn" to={`/practice/${q.topicId}`}>टॉपिक खोलें</Link><button className="btn" onClick={()=>useProgressStore.getState().toggleBookmarkQuestion(q.id)}>हटाएँ</button></div></Card>)}</div>:<Card className="empty"><h2>अभी कोई बुकमार्क नहीं</h2><p>अभ्यास करते समय प्रश्न सुरक्षित करें।</p><Link className="btn primary" to="/subjects">अभ्यास शुरू करें</Link></Card>}</Shell>};
const MockTests=()=> <Shell><div className="page-head"><h1>मॉक टेस्ट</h1><p>वास्तविक परीक्षा पैटर्न के अनुसार अभ्यास करें।</p></div><Card><h2>JNVST कक्षा 9 पूर्ण मॉक टेस्ट</h2><p>अंग्रेज़ी 15 · हिंदी 15 · गणित 35 · सामान्य विज्ञान 35</p><p><b>100 प्रश्न · 150 मिनट</b></p><Link className="btn primary" to="/mock-tests/full">टेस्ट शुरू करें</Link></Card></Shell>;
const MockEngine=()=>{const qs=useMemo(()=>[...allQuestions.filter(q=>q.subjectId==='sub_eng').slice(0,15),...allQuestions.filter(q=>q.subjectId==='sub_hin').slice(0,15),...allQuestions.filter(q=>q.subjectId==='sub_math').slice(0,35),...allQuestions.filter(q=>q.subjectId==='sub_sci').slice(0,35)],[ ]);const [idx,setIdx]=useState(0);const [answers,setAnswers]=useState<Record<string,string[]>>({});const [done,setDone]=useState(false);const q=qs[idx];if(done){const score=qs.reduce((n,x)=>{const a=answers[x.id]||[];return n+(a.length===x.correctOptionIds.length&&a.every(v=>x.correctOptionIds.includes(v))?1:0)},0);return <Shell><Card><h1>मॉक टेस्ट परिणाम</h1><div className="result-score">{score} / 100</div><p>आपका परिणाम इसी ब्राउज़र में सुरक्षित किया गया है।</p><Link className="btn primary" to="/mock-tests">मॉक टेस्ट पर जाएँ</Link></Card></Shell>}if(!q)return <Shell><Card><h1>मॉक टेस्ट उपलब्ध नहीं है</h1><Link to="/">डैशबोर्ड</Link></Card></Shell>;const sel=answers[q.id]||[];const toggle=(id:string)=>setAnswers(a=>({...a,[q.id]:(q.type==='mcq'||q.type==='true-false')?[id]:sel.includes(id)?sel.filter(x=>x!==id):[...sel,id]}));return <Shell><div className="mockbar"><b>JNVST मॉक टेस्ट</b><span>{idx+1} / 100</span></div><Card className="quiz"><QuestionText blocks={q.text}/><div className="options">{q.options.map(o=><button key={o.id} className={`option ${sel.includes(o.id)?'selected':''}`} onClick={()=>toggle(o.id)}><span className="radio">{sel.includes(o.id)?'✓':''}</span>{o.text}</button>)}</div><div className="quiz-actions"><button className="btn" disabled={!idx} onClick={()=>setIdx(i=>i-1)}>पिछला</button>{idx===99?<button className="btn primary" onClick={()=>setDone(true)}>जमा करें</button>:<button className="btn primary" onClick={()=>setIdx(i=>i+1)}>अगला</button>}</div></Card></Shell>};
const AppRoutes=()=> <Routes><Route path="/" element={<Dashboard/>}/><Route path="/subjects" element={<SubjectsPage/>}/><Route path="/subjects/:subjectId" element={<SubjectPage/>}/><Route path="/practice/:topicId" element={<Practice/>}/><Route path="/bookmarks" element={<Bookmarks/>}/><Route path="/mock-tests" element={<MockTests/>}/><Route path="/mock-tests/full" element={<MockEngine/>}/><Route path="*" element={<Shell><Card><h1>पृष्ठ नहीं मिला</h1><Link to="/">डैशबोर्ड पर जाएँ</Link></Card></Shell>}/></Routes>;
export default function App(){return <HashRouter><AppRoutes/></HashRouter>}
